# Generated by Django 4.2.7 on 2025-08-06 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0001_initial'),
        ('workflows', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('received', 'Received')], default='dispatched', max_length=20)),
                ('expected_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transits', to='applications.applicationform')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transits_from', to='locations.location')),
                ('from_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transits_sent', to='workflows.workflowstep')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transits_to', to='locations.location')),
                ('to_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transits_received', to='workflows.workflowstep')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
