# Generated by Django 4.2.7 on 2025-08-06 09:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='relationship_to_claimant',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='relationship',
        ),
        migrations.AddField(
            model_name='assessment',
            name='worker_assessment',
            field=models.TextField(default='WAS NOT ASSESSED'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('divorced', 'Divorced'), ('annulled', 'Annulled'), ('cohabiting', 'Cohabiting / Live-in'), ('unknown', 'Prefer not to say')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='contact_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='educational_attainment',
            field=models.CharField(blank=True, choices=[('none', 'No Formal Education'), ('elem_incomplete', 'Elementary Level (Incomplete)'), ('elem_graduate', 'Elementary Graduate'), ('hs_incomplete', 'High School Level (Incomplete)'), ('hs_graduate', 'High School Graduate'), ('shs_incomplete', 'Senior High School (Incomplete)'), ('shs_graduate', 'Senior High School Graduate'), ('vocational', 'Vocational Graduate'), ('college_incomplete', 'College Level (Incomplete)'), ('college_graduate', 'College Graduate'), ('postgrad', 'Postgraduate / Master’s Degree'), ('doctorate', 'Doctoral Degree / PhD')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='extension_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, 'Unknown'), ('male', 'Male'), ('female', 'Female')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='claimant',
            name='age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='claimant',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('divorced', 'Divorced'), ('annulled', 'Annulled'), ('cohabiting', 'Cohabiting / Live-in'), ('unknown', 'Prefer not to say')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='claimant',
            name='educational_attainment',
            field=models.CharField(blank=True, choices=[('none', 'No Formal Education'), ('elem_incomplete', 'Elementary Level (Incomplete)'), ('elem_graduate', 'Elementary Graduate'), ('hs_incomplete', 'High School Level (Incomplete)'), ('hs_graduate', 'High School Graduate'), ('shs_incomplete', 'Senior High School (Incomplete)'), ('shs_graduate', 'Senior High School Graduate'), ('vocational', 'Vocational Graduate'), ('college_incomplete', 'College Level (Incomplete)'), ('college_graduate', 'College Graduate'), ('postgrad', 'Postgraduate / Master’s Degree'), ('doctorate', 'Doctoral Degree / PhD')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='claimant',
            name='extension_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='claimant',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, 'Unknown'), ('male', 'Male'), ('female', 'Female')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='claimant',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='claimant',
            name='occupation',
            field=models.TextField(blank=True, default='None'),
        ),
        migrations.AddField(
            model_name='claimant',
            name='relationship_to_beneficiary',
            field=models.CharField(choices=[('self', 'Self'), ('spouse', 'Spouse'), ('child', 'Child'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('grandparent', 'Grandparent'), ('grandchild', 'Grandchild')], default='self', max_length=12),
        ),
        migrations.AddField(
            model_name='claimant',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='familymember',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='educational_attainment',
            field=models.CharField(blank=True, choices=[('none', 'No Formal Education'), ('elem_incomplete', 'Elementary Level (Incomplete)'), ('elem_graduate', 'Elementary Graduate'), ('hs_incomplete', 'High School Level (Incomplete)'), ('hs_graduate', 'High School Graduate'), ('shs_incomplete', 'Senior High School (Incomplete)'), ('shs_graduate', 'Senior High School Graduate'), ('vocational', 'Vocational Graduate'), ('college_incomplete', 'College Level (Incomplete)'), ('college_graduate', 'College Graduate'), ('postgrad', 'Postgraduate / Master’s Degree'), ('doctorate', 'Doctoral Degree / PhD')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, 'Unknown'), ('male', 'Male'), ('female', 'Female')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='government_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familymember',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='issue_description',
            field=models.TextField(default='WAS NOT DETERMINED'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='risk_level',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='claimant',
            name='contact_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='claimant',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
