# Generated by Django 4.2.7 on 2025-08-06 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printed_at', models.DateTimeField(auto_now_add=True)),
                ('print_details', models.TextField(blank=True, help_text='Printer settings, number of copies, etc.')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_logs', to='applications.applicationform')),
                ('printed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
